version: 2

sources:
  - name: Actividad2
    database: mineria-uninorte
    tables:
      - name: Clientes_EXT
        description: tabla de clientes Externa
      - name: Compras_EXT
        description: tabla de compras Externa
      - name: Exito_EXT
        description: tabla de productos de exito Externa
      - name: Olimpica_EXT
        description: tabla de produtos de olimpica Externa


      
      